import { TextVariantsEnum } from '@components/Text';

export const data = [
  {
    id: 1,
    text_variant: TextVariantsEnum.Heading_1,
    text_variant_des: TextVariantsEnum.Subtitle_S,
    text: 'Heading 1',
    type: 'Bold',
    font_size: 34,
    line_height: 38,
  },
  {
    id: 2,
    text_variant: TextVariantsEnum.Heading_2,
    text_variant_des: TextVariantsEnum.Subtitle_S,
    text: 'Heading 2',
    type: 'Bold',
    font_size: 28,
    line_height: 36,
  },
  {
    id: 3,
    text_variant: TextVariantsEnum.Heading_3,
    text_variant_des: TextVariantsEnum.Subtitle_S,
    text: 'Heading 3',
    type: 'Bold',
    font_size: 24,
    line_height: 30,
  },
  {
    id: 4,
    text_variant: TextVariantsEnum.Heading_4,
    text_variant_des: TextVariantsEnum.Subtitle_S,
    text: 'Heading 4',
    type: 'Bold',
    font_size: 20,
    line_height: 24,
  },
  {
    id: 5,
    text_variant: TextVariantsEnum.Heading_5,
    text_variant_des: TextVariantsEnum.Subtitle_S,
    text: 'Heading 5',
    type: 'Bold',
    font_size: 18,
    line_height: 24,
  },
  {
    id: 6,
    text_variant: TextVariantsEnum.Subtitle_M,
    text_variant_des: TextVariantsEnum.Subtitle_S,
    text: 'Subtitle M',
    type: 'Bold',
    font_size: 16,
    line_height: 20,
  },
  {
    id: 7,
    text_variant: TextVariantsEnum.Subtitle_S,
    text_variant_des: TextVariantsEnum.Subtitle_S,
    text: 'Subtitle S',
    type: 'Bold',
    font_size: 14,
    line_height: 20,
  },
  {
    id: 8,
    text_variant: TextVariantsEnum.Body_L,
    text_variant_des: TextVariantsEnum.Subtitle_S,
    text: 'Body L',
    type: 'Medium',
    font_size: 16,
    line_height: 20,
  },
  {
    id: 9,
    text_variant: TextVariantsEnum.Body_M,
    text_variant_des: TextVariantsEnum.Subtitle_S,
    text: 'Body M',
    type: 'Medium',
    font_size: 14,
    line_height: 20,
  },
  {
    id: 10,
    text_variant: TextVariantsEnum.Caption,
    text_variant_des: TextVariantsEnum.Subtitle_S,
    text: 'Caption',
    type: 'Medium',
    font_size: 12,
    line_height: 16,
  },
];
